// dsakiko_webui/frontend/src/live2d/Live2DStage.jsx
import { useEffect, useRef, useState } from 'react'
import { Application, Ticker, UPDATE_PRIORITY } from 'pixi.js'
import {
  Live2DModel,
  MotionPriority,
} from 'pixi-live2d-display/cubism2'

Live2DModel.registerTicker(Ticker)

export function Live2DStage({
  modelUrl,
  active,
  motionGroup,
  mouthOpenRef,
}) {
  const hostRef = useRef(null)
  const appRef = useRef(null)
  const modelRef = useRef(null)
  const activeRef = useRef(active)
  const [status, setStatus] = useState('loading')
  const [error, setError] = useState('')

  useEffect(() => {
    const host = hostRef.current
    if (!host || !modelUrl) return undefined

    let app
    let model
    let resizeObserver
    let disposed = false

    const fitModel = () => {
      if (!app || !model || disposed) return
      const width = app.screen.width
      const height = app.screen.height
      if (width <= 0 || height <= 0) return

      model.scale.set(1)
      const scale = Math.min(
        (width * 1.2) / model.width,
        (height * 1.3) / model.height,
      )
      model.scale.set(scale)
      model.position.set(width / 2, height * 0.5)
    }

    const resizeCanvas = () => {
      if (!app || disposed) return
      app.renderer.resize(
        Math.max(host.clientWidth, 1),
        Math.max(host.clientHeight, 1),
      )
      fitModel()
    }

    const load = async () => {
      setStatus('loading')
      setError('')
      try {
        if (!window.Live2D) {
          throw new Error('Cubism 2 Core 未加载')
        }

        app = new Application({
          antialias: true,
          autoDensity: true,
          backgroundAlpha: 0,
          resolution: Math.min(window.devicePixelRatio || 1, 2),
        })
        app.view.className = 'live2d-canvas'
        host.replaceChildren(app.view)
        appRef.current = app

        resizeObserver = new ResizeObserver(resizeCanvas)
        resizeObserver.observe(host)
        resizeCanvas()

        model = await Live2DModel.from(modelUrl, {
          autoInteract: false,
          idleMotionGroup: 'idle_motion',
        })
        if (disposed) {
          model.destroy({ children: true })
          return
        }

        model.anchor.set(0.5, 0.5)
        modelRef.current = model
        app.stage.addChild(model)
        fitModel()

        app.ticker.add(() => {
          const coreModel = modelRef.current?.internalModel?.coreModel
          if (!coreModel?.setParamFloat) return
          coreModel.setParamFloat(
            'PARAM_MOUTH_OPEN_Y',
            Math.min(1, mouthOpenRef.current * 1.35),
          )
        }, undefined, UPDATE_PRIORITY.LOW)

        setStatus('ready')
        if (!activeRef.current) app.ticker.stop()
      } catch (loadError) {
        if (disposed) return
        console.error('Live2D model loading failed:', loadError)
        setStatus('error')
        setError(loadError instanceof Error ? loadError.message : String(loadError))
      }
    }

    load()

    return () => {
      disposed = true
      resizeObserver?.disconnect()
      modelRef.current = null
      appRef.current = null
      if (app) {
        app.destroy(true, {
          children: true,
          texture: true,
          baseTexture: true,
        })
      }
    }
  }, [modelUrl, mouthOpenRef])

  useEffect(() => {
    activeRef.current = active
    const ticker = appRef.current?.ticker
    if (!ticker) return
    if (active) ticker.start()
    else ticker.stop()
  }, [active])

  useEffect(() => {
    const model = modelRef.current
    if (!active || status !== 'ready' || !model || !motionGroup) return
    if (motionGroup === 'idle_motion') return
    model.motion(motionGroup, undefined, MotionPriority.FORCE).catch(() => {})
  }, [active, motionGroup, status])

  return (
    <div className="live2d-stage" aria-label="Live2D 角色">
      <div ref={hostRef} className="live2d-stage__canvas" />
      {status === 'loading' && (
        <div className="stage-status" role="status">
          <span className="loading-spinner" aria-hidden="true" />
          <span>角色载入中</span>
        </div>
      )}
      {status === 'error' && (
        <div className="stage-status stage-status--error" role="alert">
          <strong>角色加载失败</strong>
          <span>{error}</span>
        </div>
      )}
    </div>
  )
}

// electron_frontend/src/renderer/components/Live2DStage.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import type { Application, Ticker } from 'pixi.js'
import { Live2DRendererController } from '../renderer-controller'

const props = defineProps<{ modelPath?: string; modelKey?: string; modelToken?: string; rendererId?: string }>()
const emit = defineEmits<{
  rendererControllerReady: [controller: Live2DRendererController]
  rendererFact: [fact: { type: string; event_id?: string; data: Record<string, any> }]
}>()

const canvasContainer = ref<HTMLDivElement>()
let app: Application | null = null
let controller: Live2DRendererController | null = null
let resizeObserver: ResizeObserver | null = null
let resizeFrame: number | null = null
let disposed = false

function onCanvasClick(e: MouseEvent) {
  if (controller && canvasContainer.value) {
    controller.handleClick(e.clientX, canvasContainer.value.clientWidth)
  }
}

onMounted(async () => {
  disposed = false
  const { Application, Ticker } = await import('pixi.js')
  const { Live2DModel } = await import('pixi-live2d-display')

  if (disposed) return

  const canvas = canvasContainer.value?.querySelector('canvas') as HTMLCanvasElement
  if (!canvas) return

  app = new Application({
    view: canvas,
    width: canvasContainer.value!.clientWidth,
    height: canvasContainer.value!.clientHeight,
    backgroundAlpha: 0,
    antialias: true,
    resolution: window.devicePixelRatio || 1,
    autoDensity: true,
  })

  if (disposed) {
    app.destroy(true)
    app = null
    return
  }

  try {
    // Model selection is authoritative Python state.  A cold Electron
    // renderer stays an inert runtime until the owner sends switch_live2d.
    if (!props.modelPath) {
      console.log('[Live2DStage] Waiting for authoritative model command')
      return
    }
    const modelSrc = props.modelPath
    const key = props.modelKey || 'live2d'
    // The package root combines Cubism 2 and Cubism 4 adapters and selects
    // the correct loader from the model JSON, preserving V2 and V3/V4.
    Live2DModel.registerTicker(Ticker)
    const live2dModel = await Live2DModel.from(modelSrc, { autoInteract: false })

    if (disposed) {
      ;(live2dModel as any).destroy?.({ children: true })
      return
    }

    // Electron 默认窗口尺寸是 450x600。这个基准必须在换模时保持稳定；
    // 如果把当前窗口尺寸当作基准，窗口缩小后换模会把模型缩放重置回 0.3。
    // 窗口尺寸改变和模型重载都通过同一公式计算，确保换模不会改变视觉比例。
    const baseScale = 0.3
    const referenceWidth = 450
    const referenceHeight = 600
    let lastWidth = 0
    let lastHeight = 0
    const applyResize = () => {
      resizeFrame = null
      if (!app || !canvasContainer.value) return
      const width = Math.max(1, canvasContainer.value.clientWidth)
      const height = Math.max(1, canvasContainer.value.clientHeight)
      if (width === lastWidth && height === lastHeight) return
      lastWidth = width
      lastHeight = height
      app.renderer.resize(width, height)
      const ratio = Math.min(width / referenceWidth, height / referenceHeight)
      live2dModel.scale.set(baseScale * ratio)
      live2dModel.x = width / 2
      live2dModel.y = height / 2
    }
    const scheduleResize = () => {
      if (resizeFrame !== null) return
      resizeFrame = requestAnimationFrame(applyResize)
    }
    live2dModel.anchor.set(0.5, 0.5)
    applyResize()
    resizeObserver = new ResizeObserver(scheduleResize)
    resizeObserver.observe(canvasContainer.value!)
    app.stage.addChild(live2dModel)

    // 行为选择由 Python controller 完成；renderer 只执行指定 group/index。
    controller = new Live2DRendererController(live2dModel, Ticker.shared, key, (fact) => emit('renderer-fact', {
      ...fact,
      data: { ...fact.data, model_token: props.modelToken || '' },
    }), props.rendererId || key, props.modelToken || '', /\.model3\.json$/i.test(modelSrc) ? 'v3' : 'v2', modelSrc)
    controller.start()
    emit('rendererControllerReady', controller)
    console.log('[Live2DStage] Model loaded, renderer controller started')
  } catch (e) {
    console.error('[Live2DStage] Failed to load model:', e)
    emit('renderer-fact', {
      type: 'renderer_unavailable',
      data: {
        model_token: props.modelToken || '',
        renderer_id: props.rendererId || props.modelKey || 'electron-renderer',
        reason: String(e),
      },
    })
  }
})

onUnmounted(() => {
  disposed = true
  resizeObserver?.disconnect()
  resizeObserver = null
  if (resizeFrame !== null) cancelAnimationFrame(resizeFrame)
  resizeFrame = null
  controller?.destroy()
  controller = null
  app?.destroy(true)
})
</script>

<template>
  <div ref="canvasContainer" class="live2d-container" @click="onCanvasClick">
    <canvas></canvas>
  </div>
</template>

<style scoped>
.live2d-container {
  width: 100%;
  height: 100%;
  position: absolute;
  top: 0;
  left: 0;
}
.live2d-container canvas {
  width: 100%;
  height: 100%;
  display: block;
}
</style>
